version: 2.1
orbs:
  codecov: codecov/codecov@1.0.2
jobs:
  build:
    docker:
      - image: circleci/python:3.8.1-buster
    steps:
      - checkout
      - run:
          name: Setup locales
          command: |
            sudo sed -i -e 's/# de_DE.UTF-8/de_DE.UTF-8/g' /etc/locale.gen
            sudo locale-gen
      - run:
          name: Install Python dependencies in a venv
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install poetry
            poetry install
      - run: 
          name: Run tests
          command: |
            . venv/bin/activate
            make test
      - codecov/upload:
          file: ".converage" 
